ktor:
  deployment:
    port: ${PORT:8080}
  application:
    modules:
      - xyz.konyahin.ExposedKt.configureExposed
      - xyz.konyahin.RoutingKt.configureRouting

db:
  path: "${DB_PATH:./data.db}"
  driver: "org.sqlite.JDBC"
